### ISSUE TITLE
There is a qwirk in the imbedded chunk of a license

### ISSUE THREAD

**Issue by fortnum** [BartJongejan/Bracmat#10]
Hi! Many thanks for your great work. I've just started on the language and it seems to me a great thing. Here is a reference on the line in source code. Not essential, but it says: "PROVIDE THE PROGRAM AS IS WITHOUT WARRANTY OF ANY <ins>Child</ins>, EITHER EXPRESSED OR IMPLIED".

https://github.com/BartJongejan/Bracmat/blob/ec4c891a74864dae3c971bad2c6c70eddf3a4848/src/bracmat.c#L16567

**Comment by BartJongejan** [comment]
Thank you for noticing this typo and telling me. The cause of the error that I once decided to translate many Dutch variable names and field names to English. The Dutch word "kind" translates to "child".

**Comment by BartJongejan** [comment]
Thank you for noticing this typo and telling me. The cause of the error that I once decided to translate many Dutch variable names and field names to English. The Dutch word "kind" translates to "child".
