### ISSUE TITLE
No unicaseconv.c unichartypes.c files in the src folder

### ISSUE THREAD

**Issue by xtradev** [BartJongejan/Bracmat#12]
During a build from the latest checkout I've got this:

    make[1]: Entering directory '/home/roman/lab/aur/bracmat-git/src/Bracmat/src'
    make[1]: *** No rule to make target 'unicaseconv.c', needed by 'bracmat'.  Stop.
    make[1]: Leaving directory '/home/roman/lab/aur/bracmat-git/src/Bracmat/src'

It seems that files `unicaseconv.c unichartypes.c` are present in the `potu` folder, but not in the `src` folder, while being referenced in the `src/Makefile`. If I link them from `potu` to `src` the build works.

**Comment by BartJongejan** [comment]
I have added the missing files, and also the script to create them (UnicodeData.bra in the root).
