### ISSUE TITLE
"xmlio" library mentioned on Rosetta Code

### ISSUE THREAD

**Issue by celtic-coder** [BartJongejan/Bracmat#16]
Hi Bart (@BartJongejan),

The [Create an HTML table](https://rosettacode.org/wiki/Create_an_HTML_table#Bracmat) task on Rosetta Code makes reference to external library "xmlio.bra", _a library that converts from Bracmat format to XML or HTML_. I did a search of your repos on GitHub but could not find this file.

Is this a separate library or has its functionality become part of the main Bracmat application?

Kind Regards,
Liam O'Brien

**Comment by BartJongejan** [comment]
Hi Liam  
You are right. Thank you for pointing that out. The predefined function toML$ does the same as (XMLIO.convert)$. Today, I tried to update the code, but I haven't found out how to log in to Rosettacode. It seems that my old account for user 'Bart' works for logging on to Discord, but rosettacode.org won't let me in. And I don't know what Discord is for.

Kind regards,
Bart Jongejan

**Comment by celtic-coder** [comment]
Hi Bart (@BartJongejan),

Thank you for getting back to me on this issue! I now see the "toML$" predefined function in the documentation and will check it out when I have the opportunity.

Rosetta Code continues to use the MedaiWiki format, but in recent months changed to using [Miraheze](https://meta.miraheze.org/wiki/FAQ) for their hosting. As with any migration there have been some problems. Perhaps you account access might have been one of them?

Did you join the Rosetta Code Discord yesterday as "Bart#5685"? The [#account-help](https://discord.com/channels/1011262808001880065/1016386259217825832) channel deals with password problems or old contributions being no longer available. Perhaps, you might put in a question in this channel to deal with your access?

Kind Regards,
Liam

**Comment by BartJongejan** [comment]
I have edited the Bracmat code of the Create_an_HTML_table page.

**Comment by celtic-coder** [comment]
Hi Bart (@BartJongejan),

Great to see that you can now edit the Rosetta Code examples again. Thanks for making this change!

Kind Regards,
Liam
