### ISSUE TITLE
escape operator's rhs

### ISSUE THREAD

**Issue by xtradev** [BartJongejan/Bracmat#2]
I am reading Help -> Escaping operator in patterns.
There is a statement:
The escape operator only affects the top node of the **escape** operator's rhs.
Should it be read as:
The escape operator only affects the top node of the **match** operator's rhs.
?

**Comment by BartJongejan** [comment]
No, there was no mistake in the help text. I have added some more examples to explain what exactly the escape operator affects and what stays outside its reach. Please download the bracmat.html file that I have just uploaded and jump to #escappattxt.

Thank you for your questions and remarks, I appreciate them.

**Comment by xtradev** [comment]
Thanks, Bart. The examples make it clear.
